apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecrets.secretName }}
  labels:
    {{- include "famouschart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  QUOTES_USER: cXVvdGVz
  QUOTES_PASSWORD: cXVvdGVzcHdk
