FROM

MAINTAINER Your Name <youremail>

ENV PORT
ENV HTTPD_CONFIG_FILE 

RUN yum install -y httpd && \
    yum clean all

RUN sed -ri -e "/^Listen 80/c\Listen ${PORT}" ${HTTPD_CONFIG_FILE} && \
    chown -R apache:apache /etc/httpd/logs/ && \
    chown -R apache:apache /run/httpd/

USER apache

# Expose the custom port that you provided in the ENV var
EXPOSE ${PORT}

# Copy all files under src/ folder to Apache DocumentRoot (/var/www/html)

# Start Apache in the foreground
